language: python
python:
  - "2.7"
  - "3.4"
branches:
  only:
    - master
before_install:
  # Icarus Verilog simulator
  - sudo apt-get install -qq -y iverilog
  # GHDL (0.33 or greater is required, not available in repository.
  # Temporarily pull 0.33 .deb from sourceforge and install
  - wget http://netcologne.dl.sourceforge.net/project/ghdl-updates/Builds/ghdl-0.33/debian/ghdl_0.33-1ubuntu1_amd64.deb
  - sudo dpkg -i ghdl_0.33-1ubuntu1_amd64.deb
  # Nose code coverage
  - pip install -q nosexcover
install:
  - python setup.py install
script:
  - nosetests --with-doctest --with-xcoverage --with-xunit --cover-package=chiptools --cover-erase
